[33mWARNING [0m retry.api:api.py:40 HTTPSConnectionPool(host='aip.baidubce.com', port=443): Max retries exceeded with url: /rest/2.0/ocr/v1/accurate_basic?access_token=24.9797858ce792404d1806319426ad507e.2592000.1733760642.282335-116013213 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))), retrying in 1 seconds...